### ISSUE TITLE
Add Automatic Cloud Builds to PRs

### ISSUE THREAD

**Issue by Fleshgrinder** [trivago/rumi#23]
We could use Travis (Linux) and AppVeyor (Windows) to run them.

No clue how we can cover BSD (Mac OS).

**Comment by markuspoerschke** [comment]
Travis CI will be done in #25

**Comment by jakubsacha** [comment]
I guess what @Fleshgrinder meant is to have some sample (always stable) project that would use the latest rumi to execute tests and ensure that rumi works.

**Comment by Fleshgrinder** [comment]
Executing the unit tests is wise too but as @jakubsacha said, the actual goal is a full integration test that ensures that rumi works as intended. Hence, I would merge the pull request for the unit tests but this issue is not done with that.

**Comment by jakubsacha** [comment]
solved by #25
